from __future__ import annotations

from typing import Any

from fsffl.behavioral.models import OwnerBehaviorProfile
from fsffl.opportunity.frontier import make_frontier_point
from fsffl.opportunity.frontier_search import FrontierSearchPolicy, explore_negotiation_frontier
from fsffl.opportunity.models import (
    ActionAuthority,
    CandidateReason,
    DiscoveryStatus,
    EvidenceCompleteness,
    OpportunityCandidate,
    OpportunityKind,
)
from fsffl.opportunity.trade_evaluation import candidate_from_trade_evaluation
from fsffl.opportunity.trade_universe import (
    TradePackageSeed,
    TradeSearchBounds,
    build_team_trade_inventory,
    canonical_package_id,
)
from fsffl.trade_decision import (
    BilateralTradeDecision,
    TradeAcceptanceView,
    assess_negotiation_feasibility,
)
from fsffl.trade_decision.models import BilateralTradeProposal, TradeLeg

from .trade_analysis_runtime import build_private_beta_trade_analysis


_PRODUCT_MODEL_VERSION = "next8-negotiation-frontier-v1"


def _package(team_id: str, assets) -> TradePackageSeed:
    items = tuple(assets)
    return TradePackageSeed(
        team_id=team_id,
        assets=items,
        canonical_id=canonical_package_id(team_id, items),
    )


def _proposal(point, *, as_of) -> BilateralTradeProposal:
    return BilateralTradeProposal(
        proposal_id=point.point_id,
        as_of=as_of,
        side_a=TradeLeg(team_id=point.focal_package.team_id, sends=point.focal_package.assets),
        side_b=TradeLeg(team_id=point.counterparty_package.team_id, sends=point.counterparty_package.assets),
        model_version=f"{_PRODUCT_MODEL_VERSION}:proposal",
    )


def _incomplete_candidate(point, runtime) -> OpportunityCandidate:
    return OpportunityCandidate(
        candidate_id=point.point_id,
        kind=OpportunityKind.PRICE_DISCOVERY,
        focal_team_id=point.focal_package.team_id,
        league_state_id=runtime.league_state.state_id,
        as_of=runtime.league_state.as_of,
        discovery_status=DiscoveryStatus.EVALUATED,
        action_authority=ActionAuthority.DIAGNOSTIC_ONLY,
        evidence_completeness=EvidenceCompleteness.PARTIAL,
        reasons=(CandidateReason.INCOMPLETE_EVIDENCE,),
        search_model_version=_PRODUCT_MODEL_VERSION,
    )


def _asset_label(league_state, asset) -> str:
    if asset.kind == "player":
        player = next((item for item in league_state.players if item.player_id == asset.player_id), None)
        return player.full_name if player is not None else asset.player_id
    if asset.kind == "pick":
        pick = next((item for item in league_state.draft_picks if item.pick_id == asset.pick_id), None)
        if pick is None:
            return asset.pick_id
        return f"{pick.season} Round {pick.round} pick"
    return f"{asset.amount} FAAB"


def build_negotiation_frontier(
    runtime: Any,
    proposal: BilateralTradeProposal,
    *,
    focal_team_id: str,
    counterparty_behavior_profile: OwnerBehaviorProfile | None = None,
    max_depth: int = 2,
    max_evaluations: int = 100,
) -> dict[str, object]:
    """Explore adjacent owned packages through NEXT-6 Search and NEXT-5 Decision.

    Search does not balance packages by changing Value. Every point is a canonical
    owned-asset package pair generated by NEXT-6 frontier geometry. Each point is
    routed through the same NEXT-5 Decision adapter as Trade Center. When a
    historical owner profile is available it travels through NEXT-5's behavioral
    evidence contract; it never becomes an acceptance percentage or Value change.
    """

    league_state = runtime.league_state
    if league_state is None:
        raise ValueError("negotiation frontier requires a loaded league state")
    if focal_team_id not in {proposal.side_a.team_id, proposal.side_b.team_id}:
        raise ValueError("focal team must be one side of the frontier seed")

    focal_leg = proposal.side_a if proposal.side_a.team_id == focal_team_id else proposal.side_b
    counter_leg = proposal.side_b if proposal.side_a.team_id == focal_team_id else proposal.side_a
    max_seed_size = max(len(focal_leg.sends), len(counter_leg.sends))
    bounds = TradeSearchBounds(
        max_assets_per_side=min(6, max(max_seed_size + 1, 2)),
        include_players=True,
        include_picks=True,
        include_faab=False,
    )
    focal_inventory = build_team_trade_inventory(league_state, team_id=focal_leg.team_id, bounds=bounds)
    counter_inventory = build_team_trade_inventory(league_state, team_id=counter_leg.team_id, bounds=bounds)
    seed = make_frontier_point(
        _package(focal_leg.team_id, focal_leg.sends),
        _package(counter_leg.team_id, counter_leg.sends),
    )

    detail_by_point: dict[str, dict[str, object]] = {}

    def evaluator(point) -> OpportunityCandidate:
        point_proposal = _proposal(point, as_of=league_state.as_of)
        analysis = build_private_beta_trade_analysis(
            runtime,
            point_proposal,
            focal_team_id=focal_team_id,
            counterparty_behavior_profile=counterparty_behavior_profile,
        )
        decision_payload = analysis.get("decision")
        if decision_payload is None:
            candidate = _incomplete_candidate(point, runtime)
            detail_by_point[point.point_id] = {
                "decision_shape": None,
                "feasibility_shape": "incomplete",
                "behavioral_evidence": analysis.get("behavioral_context") is not None,
                "action_authority": candidate.action_authority.value,
                "reasons": [reason.value for reason in candidate.reasons],
            }
            return candidate

        decision = BilateralTradeDecision.model_validate(decision_payload)
        acceptance_payload = analysis.get("behavioral_context")
        acceptance = (
            TradeAcceptanceView.model_validate(acceptance_payload)
            if acceptance_payload is not None
            else None
        )
        feasibility = assess_negotiation_feasibility(
            decision,
            focal_team_id=focal_team_id,
            acceptance=acceptance,
            model_version=f"{_PRODUCT_MODEL_VERSION}:feasibility",
        )
        complete = bool(analysis.get("availability", {}).get("roster_consequences"))
        candidate = candidate_from_trade_evaluation(
            candidate_id=point.point_id,
            focal_team_id=focal_team_id,
            league_state_id=league_state.state_id,
            as_of=league_state.as_of,
            feasibility=feasibility,
            evidence_completeness=(
                EvidenceCompleteness.COMPLETE if complete else EvidenceCompleteness.PARTIAL
            ),
            acceptance=acceptance,
            disposition=None,
            search_model_version=_PRODUCT_MODEL_VERSION,
        )
        detail_by_point[point.point_id] = {
            "decision_shape": decision.shape.value,
            "feasibility_shape": feasibility.shape.value,
            "behavioral_evidence": acceptance is not None,
            "action_authority": candidate.action_authority.value,
            "reasons": [reason.value for reason in candidate.reasons],
        }
        return candidate

    policy = FrontierSearchPolicy(
        max_depth=max_depth,
        max_evaluations=max_evaluations,
        expand_focal_side=True,
        expand_counterparty_side=True,
    )
    result = explore_negotiation_frontier(
        seed,
        focal_inventory=focal_inventory,
        counterparty_inventory=counter_inventory,
        bounds=bounds,
        evaluator=evaluator,
        policy=policy,
        search_model_version=_PRODUCT_MODEL_VERSION,
    )

    points = []
    for evaluated in result.evaluated:
        point = evaluated.point
        points.append(
            {
                "point_id": point.point_id,
                "depth": evaluated.depth,
                "is_seed": point.point_id == result.seed_point_id,
                "focal_assets": [
                    {
                        "kind": asset.kind,
                        "label": _asset_label(league_state, asset),
                        "asset": asset.model_dump(mode="json"),
                    }
                    for asset in point.focal_package.assets
                ],
                "counterparty_assets": [
                    {
                        "kind": asset.kind,
                        "label": _asset_label(league_state, asset),
                        "asset": asset.model_dump(mode="json"),
                    }
                    for asset in point.counterparty_package.assets
                ],
                **detail_by_point.get(point.point_id, {}),
            }
        )

    return {
        "seed_point_id": result.seed_point_id,
        "focal_team_id": focal_team_id,
        "counterparty_team_id": counter_leg.team_id,
        "evaluated_count": len(result.evaluated),
        "max_depth_reached": result.max_depth_reached,
        "exhausted": result.exhausted,
        "policy": policy.model_dump(mode="json"),
        "bounds": bounds.model_dump(mode="json"),
        "points": points,
        "authority": {
            "search_geometry": "NEXT-6 Opportunity frontier",
            "bilateral_consequences": "NEXT-5 Trade Decision",
            "behavioral_evidence": counterparty_behavior_profile is not None,
            "acceptance_probability": False,
            "materiality_evaluated": False,
            "market_value_rewritten": False,
        },
        "model_version": _PRODUCT_MODEL_VERSION,
    }
